.TH man 1 "1 ноября 2017 г." "0.2" "русский мануал для программы akrypt"
.SH НАЗВАНИЕ
akrypt \- консольная утилита для реализации российских криптографических преобразований.

.SH ОПИСАНИЕ

.SH СИНТАКСИС

.SH КОМАНДЫ ДЛЯ РАБОТЫ С КЛЮЧАМИ

.SH КОМАНДЫ ДЛЯ ШИФРОВАНИЯ

.SH КОМАНДЫ ДЛЯ КОНТРОЛЯ ЦЕЛОСТНОCТИ

.B icode [опции] имя

Команда, позволяющая вычислить контрольную сумму (код целостности или имитовставку)
для одного или нескольких файлов. Для выполнения команды необходимо указать либо имя одного или нескольких файлов, либо
имя каталога. В случае указания нескольких имен каталогов поиск производится в каждом из них для всех файлов к которым разрешен доступ.

Опция -p (--pattern) позволяет указать шаблон для поиска файлов при обработке каталогов.
Для операционных систем, соответствующих стандарту POSIX, шаблон поиска должен иметь вид, удовлетворяющий
формату функции fnmatch (более подробно смотри man fnmatch).

Опция -r (--recursive) указывает программе обходить каталоги рекурсивно.

Опция -a (--algorithm) позволяет определить бесключевую функцию хеширования, используемую для вычисления
контрольной суммы. Параметр опции должен являться либо именен алгоритма, либо идентификатором, представленным
в виде последовательности чисел, разделенных точками. Точные значения имен алгоритмов и их идентификаторов могут
быть получены с помощью вызова akrypt show --oid hash_function.
В случае, когда опция -a не задана, используется алгоритм "Стрибог256", регламентированный
национальным стандартом ГОСТ Р 34.11-2012.

.B Сравнение с утилитами с аналогичной функциональностью

Для сравнения были выьраны утилиты gostsum и rhash, позволяющие вычислять


user@host:~$ echo -n hello > test.file
user@host:~$ gostsum test.file

ea50649ed8d4cf1925bd2ed2a84aa2171215d78f271f65f30d0240afdb6dea92 test.file

Генерация такого же значения, как и у утилиты gosthash

user@host:~$ akrypt icode -a gosthash94 --reverse-order test.file

EA50649ED8D4CF1925BD2ED2A84AA2171215D78F271F65F30D0240AFDB6DEA92 test.file

Проверка значения, выработанного gosthash

user@host:~$ gostsum test.file > test.checksum

user@host:~$ akrypt icode -a gosthash94 --reverse-order -c test.checksum

test.file Ok

total: 1 files, where: correct 1, wrong 0.


Генерация такого же значения, как и у утилиты rhash

user@host:~$ rhash --gost-cryptopro test.file

92ea6ddbaf40020df3651f278fd7151217a24aa8d22ebd2519cfd4d89e6450ea  test.file

user@host:~$ akrypt icode -a gosthash94 test.file

92EA6DDBAF40020DF3651F278FD7151217A24AA8D22EBD2519CFD4D89E6450EA test.file


А вот на более современном алгоритме ни чего разворачивать не приходится

gost12sum test.file

3fb0700a41ce6e41413ba764f98bf2135ba6ded516bea2fae8429cc5bdd46d6d test.file

alex@kenzo:~/Works/lib/akrypt/build-libakrypt-0.x-gcc-Release$ akrypt icode test.file

3FB0700A41CE6E41413BA764F98BF2135BA6DED516BEA2FAE8429CC5BDD46D6D test.file



.SH ВСПОМОГАТЕЛЬНЫЕ И ИНФОРМАЦИОННЫЕ КОМАНДЫ

.SH ОПЦИИ

.SH ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ

.SH ПРИМЕРЫ ШИФРОВАНИЯ ИНФОРМАЦИИ

.SH ПРИМЕРЫ КОНТРОЛЯ ЦЕЛОСТНОСТИ

.B akrypt icode -rp "*.t??" -a streebog512 .

Данный вызов позволяет вычислить код целостности всех файлов, удовлетворяющих шаблону "*.t??"
(файлы, имеющие расширение из трех символов, начинающееся с символа t) в текущем каталоге,
а также во всех доступных вложенных каталогах. Для вычисления кода целостности используется
функция хеширования "Стрибог512", регламентируемая национальным стандартом ГОСТ Р 34.11-2012.

.SH СТАНДАРТЫ

Национальные стандарты Российской Федерации
 - ГОСТ Р 34.10-2012,
 - ГОСТ Р 34.11-2012,
 - ГОСТ Р 34.11-94 (в настоящее время стандарт отменен),
 - ГОСТ Р 34.12-2015,
 - ГОСТ Р 34.13-2015.

Методические рекомендации Росстандарта
 - Р 50.1.111-2016,
 - Р 50.1.113-2016

.SH АВТОР
Axel Kenzo & The Company Of Belles Lettres (с) 2014 - 2017.

Сайт проекта http://openskzi.ru
