/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -findirect-choice`
 */

#ifndef	_AbstractKey_H_
#define	_AbstractKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AbstractKey_PR {
	AbstractKey_PR_NOTHING,	/* No components present */
	AbstractKey_PR_secretKey
} AbstractKey_PR;

/* Forward declarations */
struct SecretKeyData;

/* AbstractKey */
typedef struct AbstractKey {
	AbstractKey_PR present;
	union AbstractKey_u {
		struct SecretKeyData	*secretKey;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AbstractKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AbstractKey;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SecretKeyData.h"

#endif	/* _AbstractKey_H_ */
#include <asn_internal.h>
