/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -pdu=all`
 */

#ifndef	_AsymmetricKeyResource_H_
#define	_AsymmetricKeyResource_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Validity.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AsymmetricKeyResource */
typedef Validity_t	 AsymmetricKeyResource_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AsymmetricKeyResource;
asn_struct_free_f AsymmetricKeyResource_free;
asn_struct_print_f AsymmetricKeyResource_print;
asn_constr_check_f AsymmetricKeyResource_constraint;
ber_type_decoder_f AsymmetricKeyResource_decode_ber;
der_type_encoder_f AsymmetricKeyResource_encode_der;
xer_type_decoder_f AsymmetricKeyResource_decode_xer;
xer_type_encoder_f AsymmetricKeyResource_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AsymmetricKeyResource_H_ */
#include <asn_internal.h>
