/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -pdu=all`
 */

#ifndef	_CipherKeyResource_H_
#define	_CipherKeyResource_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CipherKeyResource */
typedef unsigned long	 CipherKeyResource_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CipherKeyResource;
asn_struct_free_f CipherKeyResource_free;
asn_struct_print_f CipherKeyResource_print;
asn_constr_check_f CipherKeyResource_constraint;
ber_type_decoder_f CipherKeyResource_decode_ber;
der_type_encoder_f CipherKeyResource_encode_der;
xer_type_decoder_f CipherKeyResource_decode_xer;
xer_type_encoder_f CipherKeyResource_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CipherKeyResource_H_ */
#include <asn_internal.h>
