/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -pdu=all`
 */

#ifndef	_EncodedKeyValue_H_
#define	_EncodedKeyValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncodedKeyValue */
typedef OCTET_STRING_t	 EncodedKeyValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncodedKeyValue;
asn_struct_free_f EncodedKeyValue_free;
asn_struct_print_f EncodedKeyValue_print;
asn_constr_check_f EncodedKeyValue_constraint;
ber_type_decoder_f EncodedKeyValue_decode_ber;
der_type_encoder_f EncodedKeyValue_encode_der;
xer_type_decoder_f EncodedKeyValue_decode_xer;
xer_type_encoder_f EncodedKeyValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EncodedKeyValue_H_ */
#include <asn_internal.h>
