/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -findirect-choice`
 */

#ifndef	_KeyContainer_H_
#define	_KeyContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AbstractKey;

/* KeyContainer */
typedef struct KeyContainer {
	long	*version	/* DEFAULT 1 */;
	struct keys {
		A_SEQUENCE_OF(struct AbstractKey) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} keys;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KeyContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AbstractKey.h"

#endif	/* _KeyContainer_H_ */
#include <asn_internal.h>
