/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -findirect-choice`
 */

#include "KeyProtectParameters.h"

static int
memb_iterationCount_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_KeyProtectParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, iterationCount),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_iterationCount_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iterationCount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, encryptionSalt),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionSalt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, encryptionMode),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionMode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, encryptionIV),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionIV"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, integritySalt),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integritySalt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct KeyProtectParameters, hmacIntegrity),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hmacIntegrity"
		},
};
static const ber_tlv_tag_t asn_DEF_KeyProtectParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_KeyProtectParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* iterationCount */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 2 }, /* encryptionSalt */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -1, 1 }, /* encryptionIV */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, -2, 0 }, /* integritySalt */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 5, 0, 0 }, /* hmacIntegrity */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* encryptionMode */
};
static asn_SEQUENCE_specifics_t asn_SPC_KeyProtectParameters_specs_1 = {
	sizeof(struct KeyProtectParameters),
	offsetof(struct KeyProtectParameters, _asn_ctx),
	asn_MAP_KeyProtectParameters_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_KeyProtectParameters = {
	"KeyProtectParameters",
	"KeyProtectParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_KeyProtectParameters_tags_1,
	sizeof(asn_DEF_KeyProtectParameters_tags_1)
		/sizeof(asn_DEF_KeyProtectParameters_tags_1[0]), /* 1 */
	asn_DEF_KeyProtectParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_KeyProtectParameters_tags_1)
		/sizeof(asn_DEF_KeyProtectParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_KeyProtectParameters_1,
	6,	/* Elements count */
	&asn_SPC_KeyProtectParameters_specs_1	/* Additional specs */
};

