/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -pdu=all`
 */

#ifndef	_KeyValue_H_
#define	_KeyValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KeyValue */
typedef struct KeyValue {
	OCTET_STRING_t	 key;
	OCTET_STRING_t	 mask;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KeyValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyValue;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyValue_H_ */
#include <asn_internal.h>
