/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_KeyValue;
extern struct asn_TYPE_descriptor_s asn_DEF_EncodedKeyValue;
extern struct asn_TYPE_descriptor_s asn_DEF_CipherKeyResource;
extern struct asn_TYPE_descriptor_s asn_DEF_Validity;
extern struct asn_TYPE_descriptor_s asn_DEF_AsymmetricKeyResource;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyResource;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyProtectParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_SecretKey;
extern struct asn_TYPE_descriptor_s asn_DEF_SecretKeyData;
extern struct asn_TYPE_descriptor_s asn_DEF_KeyContainer;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module KeyContainer in KeyContainer.asn1 */
	&asn_DEF_KeyValue,	
	&asn_DEF_EncodedKeyValue,	
	&asn_DEF_CipherKeyResource,	
	&asn_DEF_Validity,	
	&asn_DEF_AsymmetricKeyResource,	
	&asn_DEF_KeyResource,	
	&asn_DEF_KeyProtectParameters,	
	&asn_DEF_SecretKey,	
	&asn_DEF_SecretKeyData,	
	&asn_DEF_KeyContainer,	
	0
};

