/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -findirect-choice`
 */

#include "SecretKey.h"

static asn_TYPE_member_t asn_MBR_SecretKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SecretKey, value),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_EncodedKeyValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SecretKey, engine),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"engine"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SecretKey, number),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"number"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SecretKey, parameters),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_KeyProtectParameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parameters"
		},
	{ ATF_POINTER, 2, offsetof(struct SecretKey, resource),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_KeyResource,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resource"
		},
	{ ATF_POINTER, 1, offsetof(struct SecretKey, description),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"description"
		},
};
static const ber_tlv_tag_t asn_DEF_SecretKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SecretKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, 0, 0 }, /* counter */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* value */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -1, 0 }, /* number */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* engine */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 5, 0, 0 }, /* description */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* parameters */
};
static asn_SEQUENCE_specifics_t asn_SPC_SecretKey_specs_1 = {
	sizeof(struct SecretKey),
	offsetof(struct SecretKey, _asn_ctx),
	asn_MAP_SecretKey_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SecretKey = {
	"SecretKey",
	"SecretKey",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SecretKey_tags_1,
	sizeof(asn_DEF_SecretKey_tags_1)
		/sizeof(asn_DEF_SecretKey_tags_1[0]), /* 1 */
	asn_DEF_SecretKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_SecretKey_tags_1)
		/sizeof(asn_DEF_SecretKey_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SecretKey_1,
	6,	/* Elements count */
	&asn_SPC_SecretKey_specs_1	/* Additional specs */
};

