/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeyContainer"
 * 	found in "KeyContainer.asn1"
 * 	`asn1c -fwide-types -pdu=all`
 */

#ifndef	_SecretKeyData_H_
#define	_SecretKeyData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecretKey.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecretKeyData */
typedef struct SecretKeyData {
	SecretKey_t	 data;
	OCTET_STRING_t	 integrityCode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecretKeyData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecretKeyData;

#ifdef __cplusplus
}
#endif

#endif	/* _SecretKeyData_H_ */
#include <asn_internal.h>
