.TH man 1 "1 августа 2017 г." "0.1" "русский мануал для программы akrypt"
.SH НАЗВАНИЕ
akrypt \- консольная утилита для реализации российских криптографических преобразований.

.SH ОПИСАНИЕ

.SH СИНТАКСИС

.SH КОМАНДЫ ДЛЯ РАБОТЫ С КЛЮЧАМИ

.SH КОМАНДЫ ДЛЯ ШИФРОВАНИЯ

.SH ВСПОМОГАТЕЛЬНЫЕ И ИНФОРМАЦИОННЫЕ КОМАНДЫ

.SH ОПЦИИ

.SH ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ

.SH ПРИМЕРЫ ШИФРОВАНИЯ ИНФОРМАЦИИ

.SH ПРИМЕРЫ КОНТРОЛЯ ЦЕЛОСТНОСТИ

.SH СТАНДАРТЫ

.SH АВТОР
Axel Kenzo & The Company Of Belles Lettres (с) 2014 - 2017.

Сайт проекта http://openskzi.ru
